### ISSUE TITLE
How can I overwrite config.js?

### ISSUE THREAD

**Issue by ghost** [brunoscopelliti/poker-holdem-engine#2]
Is it possible? Inside the code it looks like it's not possible, because the default config.js is required in a relative manner all over the place.

**Comment by brunoscopelliti** [comment]
Hi,

yes, it's definetely possible.

You could override the default configuration setup, by setting the property in the configuration object as environment variable... take a look at config.js, this is the line that permit to override the default configuration:

```
Object.assign(config, process.env);
```

If you run your app on Heroku, (and probably even other similiar service) you could setting the environment variable directly from their website.

**Comment by ghost** [comment]
Thank you.
