### ISSUE TITLE
Is it production ready for real world apps? If not what are its limitations?

### ISSUE THREAD

**Issue by elieobeid7** [brunoscopelliti/poker-holdem-engine#5]

**Comment by brunoscopelliti** [comment]
Don't know how people are using this module.
It works fine for me, and I've a project online that uses this module (still locked at version 2.*, but I want to upgrade when possible).

**Comment by elieobeid7** [comment]
npm install gives

```
added 827 packages from 424 contributors and audited 18216 packages in 9.165s
found 117 vulnerabilities (102 low, 2 moderate, 13 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

npm audit fix, fixes 3 of 117 vulnerability, if you use it with --force, it fixes all of them but not sure if it breaks anything

**Comment by brunoscopelliti** [comment]
I can't tell for sure... it depends by what packages are affected.
