### ISSUE TITLE
Question: Restarting tournament after pausing

### ISSUE THREAD

**Issue by stephclleung** [brunoscopelliti/poker-holdem-engine#6]
Hello! First of all thank you for creating this engine!
This is more of a question than an issue.

I am a comp sci student trying to use this engine for a school project.
I have a question regarding on how to restart the tournament after pausing it. 

What I am trying to do is after each update, I want to pause the tournament (Which works wonderfully) and do other stuff until I ask the tournament to resume.

Here's a part of my code: 
```
//index.js
...
const thread = childProcess.fork("tournament.js");
    thread.on("message", (msg) => {
        if (msg.topic === "exit") {
            thread.kill();
        }
        else if (msg.topic == "pause now") {
            thread.send({ topic: "pause" });
        }
        else if (msg.topic == "process data") {
            //do stuff here with data
            thread.send({ topic: "restart" });
        }
...
```
and here's the script that the child process is running:
```
//tournament.js
...
let t;
process.on("message", (msg) => {
    switch (msg.topic) {
        case "create":
            t = new Tournament(tournamentID, players, tournamentSettings, { autoStart: true });
            t.on("TOURNAMENT:updated", (data, done) => {
                t.pause();
                process.send({ topic: "process data", data });
            });
            break;
        case "restart":
            t.restart();
            break;
...
```

With current code, the tournament seems to reset instead of continuing from where it left off.

here's the debug log:
```
debug: [TASK]: Increment handId
debug: [TASK]: Wait game restart
info: Tournament tester is going to restart. {"tag":"tester"}
debug: [TASK]: Wait before new hand
debug: [TASK]: Announce current hand
info: Starting hand 1/2 {"tag":"[15300] tester: 1/2"}
debug: [TASK]: Reset gamestate
debug: [TASK]: Assign Dealer button
debug: [TASK]: Set Small Blind
debug: [TASK]: Pay ANTE
debug: [TASK]: Pay Blinds
debug: [TASK]: Assign private cards
debug: [TASK]: Save setup
info: Tournament tester is going to be paused. {"tag":"tester"}
debug: [TASK]: Increment handId
```
Please let me know if I am misusing Tournament.restart(), or if you have any pointers on how to solve this. Thank you very much!

**Comment by brunoscopelliti** [comment]
I've found a couple of bugs on how I handle paused game.
There's a typo `pause` vs `paused`... but even with this sorted out the restart doesn't happen as I wanted.

Anyway, it doesn't seem strictily necessary to pause the game to obtain what you're trying to obtain.

```
t.on("TOURNAMENT:updated", (data, done) => {
                t.pause(); // <- Not strictly needed
                process.send({ topic: "process data", data });
            });
```

When `TOURNAMENT:updated` is emitted, the game won't proceed further until `done` is executed.
Hope this helps.

**Comment by brunoscopelliti** [comment]
Also, keep in mind that `tournament.pause()` is not meant to immediately pause a tournament; it waits the current hand to complete before pausing the game.
This wasn't worked as I expected; but now it should be fixed.
Let me know if it works for you too.
Thank you for reporting the issue.

**Comment by stephclleung** [comment]
Thank you for the speedy reply and fixes!
I updated my repo and I think I understand how you intended ```pause()``` and ```restart()``` to work now.

Unfortunately for us, this breaks our original logic, as we wanted to pause the tournament on each update, and wait indefinitely until the parent sends a message to the child process to continue

We are trying to do :
```
//child : tournament.js
...
process.on("message", async (msg) => {
    t.on("TOURNAMENT:updated", (data, done) => {
        process.send({ topic: "updates", data }, () => {
            //need a confirmation from index.js
            done();
         })
    }

    switch (msg.topic) {
        case "start-game":
            console.log(chalk.green("Msg = start-game | Starting !"));
            await t.start();
            break;
         case "pause":
            //stops the game until further updates
            t.pause();
            break;
        case "resume":
            //Need the above to wait until this msg comes in.
            break;
});
```
and
```
//parent : index.js
..
 thread.on("message", (msg) => {
        if (msg.topic === "exit") {
            thread.kill();
        }
        else if (msg.topic == "updates") {
            //sends a webhook to an external app
           //wait for user input from external app, collect bets etc

          //then notifies child process to continue.
           thread.send({topic : "resume"})
        }
...

```
We're very new to NodeJs / Javascript, so to me it seems like with the current structure wouldn't work out for us (since we're involving a third party app.)
Would you have any recommendations for us? 

--- EDIT ----
I think I figured it out :
```
//tournament.js
const events = require('events');
const em = new events.EventEmitter();

//Each time when PHE/Tournament.js has an update, this will catch it.
t.on("TOURNAMENT:updated", async (data, done) => {
    //Sends data to parent.
    process.send({ topic: "updates", data }, () => {
        //Runs when confirmation is recv'ed
        em.once("recieved update", (msg) => {
            done();
        })
    });
});
...

process.on("message", async (msg) => {
    switch (msg.topic) {
        ...
        case "reply":
            em.emit("recieved update");
            break;
```
where the parent would would send an update to the child once it's done processing stuff.
It's a bit clumsy, but it seems to work right now
Thank you so much again for pushing out the fixes!
